import { RiskItem, ActionItem, ACEScore } from "./types"

export const mockACEScore: ACEScore = {
  overall: 73,
  breakdown: {
    alignment: 82,
    commercialization: 68,
    execution: 71,
  },
  confidence: 89,
  timestamp: new Date(),
}

export const mockRisks: RiskItem[] = [
  {
    id: "r1",
    category: "compliance",
    title: "Missing SBIR/STTR Certification",
    description: "Your company has not completed the required SBA certification for SBIR eligibility.",
    probability: 5,
    impact: 5,
    status: "critical",
    recommendation: "Complete SBA registration and certifications before submission deadline.",
  },
  {
    id: "r2",
    category: "funding",
    title: "Budget Misalignment",
    description: "Proposed budget exceeds typical Phase I award by 23%. May trigger additional scrutiny.",
    probability: 4,
    impact: 4,
    status: "critical",
    recommendation: "Revise budget to align with agency norms ($256K average for NSF Phase I).",
  },
  {
    id: "r3",
    category: "product",
    title: "Weak Commercialization Plan",
    description: "Market analysis lacks specific TAM/SAM/SOM figures and competitive positioning.",
    probability: 4,
    impact: 3,
    status: "warning",
    recommendation: "Add detailed market sizing with sources and clear go-to-market strategy.",
  },
  {
    id: "r4",
    category: "team",
    title: "Key Personnel Gap",
    description: "No identified technical lead with relevant PhD or 10+ years industry experience.",
    probability: 3,
    impact: 4,
    status: "warning",
    recommendation: "Consider adding a technical advisor or consultant with domain expertise.",
  },
  {
    id: "r5",
    category: "ops",
    title: "Timeline Compression",
    description: "Proposed 6-month timeline is aggressive for stated technical milestones.",
    probability: 3,
    impact: 2,
    status: "manageable",
    recommendation: "Add buffer time or reduce scope of Phase I deliverables.",
  },
]

export const mockActions: ActionItem[] = [
  {
    id: "a1",
    priority: "P0",
    title: "Complete SBA Registration",
    description: "Register on SAM.gov and complete SBIR company certification to establish eligibility.",
    category: "compliance",
    owner: "Founder",
    timeline: "This Week",
    estimatedImpact: 10,
    status: "todo",
    isLocked: false,
  },
  {
    id: "a2",
    priority: "P0",
    title: "Revise Budget to $256K",
    description: "Align budget with NSF Phase I norms. Remove equipment costs over $5K threshold.",
    category: "funding",
    owner: "CFO",
    timeline: "3 Days",
    estimatedImpact: 9,
    status: "todo",
    isLocked: false,
  },
  {
    id: "a3",
    priority: "P1",
    title: "Add Market Analysis Section",
    description: "Include TAM ($4.2B), SAM ($890M), SOM ($45M) with Gartner/IDC sources.",
    category: "product",
    owner: "Product Lead",
    timeline: "1 Week",
    estimatedImpact: 8,
    status: "todo",
    isLocked: false,
  },
  {
    id: "a4",
    priority: "P1",
    title: "Recruit Technical Advisor",
    description: "Identify and secure commitment from domain expert (PhD preferred) as named advisor.",
    category: "team",
    owner: "CEO",
    timeline: "2 Weeks",
    estimatedImpact: 7,
    status: "in-progress",
    isLocked: false,
  },
  {
    id: "a5",
    priority: "P1",
    title: "Strengthen IP Position",
    description: "File provisional patent or document trade secrets before proposal submission.",
    category: "product",
    owner: "Legal",
    timeline: "2 Weeks",
    estimatedImpact: 6,
    status: "todo",
    isLocked: true,
  },
  {
    id: "a6",
    priority: "P2",
    title: "Add Letters of Support",
    description: "Secure 2-3 letters from potential customers or industry partners.",
    category: "product",
    owner: "BD Lead",
    timeline: "3 Weeks",
    estimatedImpact: 5,
    status: "todo",
    isLocked: true,
  },
  {
    id: "a7",
    priority: "P2",
    title: "Extend Timeline to 9 Months",
    description: "Revise project timeline to include realistic buffer for technical milestones.",
    category: "ops",
    owner: "PM",
    timeline: "1 Week",
    estimatedImpact: 4,
    status: "todo",
    isLocked: true,
  },
  {
    id: "a8",
    priority: "P2",
    title: "Prepare Phase II Roadmap",
    description: "Draft preliminary Phase II plan showing scale-up path and commercial timeline.",
    category: "funding",
    owner: "Strategy",
    timeline: "1 Month",
    estimatedImpact: 4,
    status: "todo",
    isLocked: true,
  },
]

export const agencyOptions = [
  { value: "nsf", label: "NSF - National Science Foundation", avgAward: "$256K" },
  { value: "nih", label: "NIH - National Institutes of Health", avgAward: "$275K" },
  { value: "dod", label: "DoD - Department of Defense", avgAward: "$250K" },
  { value: "doe", label: "DOE - Department of Energy", avgAward: "$250K" },
  { value: "nasa", label: "NASA - National Aeronautics", avgAward: "$150K" },
  { value: "usda", label: "USDA - Agriculture", avgAward: "$100K" },
]

export const industryOptions = [
  "Artificial Intelligence / ML",
  "Biotechnology",
  "Clean Energy",
  "Cybersecurity",
  "Defense Technology",
  "Digital Health",
  "FinTech",
  "Hardware / IoT",
  "SaaS / Enterprise",
  "Space Technology",
  "Other",
]

export const stageOptions = [
  { value: "pre-seed", label: "Pre-Seed", description: "Idea stage, <$500K raised" },
  { value: "seed", label: "Seed", description: "$500K - $2M raised" },
  { value: "series-a", label: "Series A", description: "$2M - $15M raised" },
  { value: "series-b", label: "Series B+", description: "$15M+ raised" },
]
